name: FTP push
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  web-deploy:
    name: Web-Deploy 🚀
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      # Runs the actual sync
      - name: 📂 Sync hidden laravel files to hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with: 
          server: philwin.bplaced.net
          username: philwin_laravel
          password: ${{ secrets.FTP_PASSWORD_LARAVEL }}

      - name: 📂 Sync public_laravel files to hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with: 
          server: philwin.bplaced.net
          username: philwin_public-laravel
          password: ${{ secrets.FTP_PASSWORD_PUBLIC_LARAVEL }}
